apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  POSTGRESQL_HOST: {{ .Values.POSTGRESQL_HOST | b64enc }}
  POSTGRESQL_USER: {{ .Values.POSTGRESQL_USER | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.POSTGRESQL_PASSWORD | b64enc }}
  POSTGRESQL_DBNAME: {{ .Values.POSTGRESQL_DBNAME | b64enc }}